<?php
/**
 * BelVG LLC.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://store.belvg.com/BelVG-LICENSE-COMMUNITY.txt
 *
 ********************************************************************
 * @category   BelVG
 * @package    BelVG_ProductTabs
 * @copyright  Copyright (c) BelVG LLC. (http://www.belvg.com)
 * @license    http://store.belvg.com/BelVG-LICENSE-COMMUNITY.txt
 */
/** \Magento\Framework\View\Element\Template $block */

/** @var \BelVG\ProductTabs\Helper\Config $config */
$config = $this->helper(\BelVG\ProductTabs\Helper\Config::class);

if ($config->isEnabled()) {
    echo $this->getChildHtml('product.info.tabs');
} else {
    echo $this->getChildHtml('product.info.details');
}
